# Generated by Django 6.0.3 on 2026-03-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThesaurusTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ka",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="ქართული ტერმინი (მაგ. ბიოლოგია)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ინგლისური შესატყვისი"
                    ),
                ),
                (
                    "definition",
                    models.TextField(blank=True, verbose_name="მეცნიერული განმარტება"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="thesaurus.thesaurusterm",
                        verbose_name="მარტივი იერარქიისთვის",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("BT", "Broader Term"),
                            ("NT", "Narrower Term"),
                            ("RT", "Related Term"),
                            ("SYN", "Synonym"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "term_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="thesaurus.thesaurusterm",
                    ),
                ),
                (
                    "term_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="thesaurus.thesaurusterm",
                    ),
                ),
            ],
            options={
                "unique_together": {("term_a", "term_b", "relation_type")},
            },
        ),
    ]
