# Generated by Django 6.0.3 on 2026-03-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("thesaurus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="კვანძის სახელი (მაგ. მაგისტრატურა, გენეტიკა)",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("School", "School"),
                            ("BSC", "Bachelor"),
                            ("MSC", "Master"),
                            ("PHD", "PhD"),
                            ("Career", "Career"),
                        ],
                        max_length=10,
                    ),
                ),
                ("summary_snippet", models.TextField(blank=True)),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="thesaurus.thesaurusterm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_label",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="გადასვლის პირობა ან მოთხოვნა",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="map.mapnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="map.mapnode",
                    ),
                ),
            ],
        ),
    ]
