# Generated by Django 5.2.10 on 2026-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='recommended_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
